@startuml
package ex42 {
 class MainParse {
  +void main()
 }

 class parsingData {
  ..member variables..
  +List<String> names
  __
  ..constructor..
  +parsingData()
  ..methods..
  +void fileReader()
  +void output()
 }

 MainParse --* parsingData : calls
}
@enduml